---
application:
  name: "Akakce"
  url: "https://www.akakce.com/"
  username: "sdurmaz77@hotmail.com"
  password: "iWifmmn3m-.YR9"

tests:
  dryrun: false
  tag: "@akakce"
  features: "src/test/resources/RegSuit/Akakce/"
  screenshots: "failure"    # failure  or  all

browser:
  name: "chrome"
  options:
    - "--start-maximized"


testerName: MO QA Team